name: CI/CD Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Build & Deploy Go API to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Build Lambda binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap ./cmd/api/main_lambda.go

      - name: Zip Lambda binary
        run: zip function.zip bootstrap

      # - name: Deploy to AWS Lambda
      #   uses: appleboy/lambda-action@v0.1.0
      #   with:
      #     function_name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
      #     region: ${{ secrets.AWS_REGION }}
      #     zip_file: function.zip
      #     access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  frontend:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Deploy to AWS Amplify (recommended: connect repo in Amplify Console)
      #   run: echo "Pushes to main will trigger Amplify build if repo is connected."

      # - name: Deploy to S3/CloudFront (alternative)
      #   uses: jakejarvis/s3-sync-action@v0.11.0
      #   with:
      #     args: --acl public-read --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     SOURCE_DIR: ./frontend/dist 